import { t as SITE } from "./site_B0-gNb8R.mjs";
import { M as InvalidComponentArgs, S as createAstro, Y as AstroError, a as renderComponent, b as unescapeHTML, f as renderTemplate, h as addAttribute, l as renderSlot, m as renderHead, o as Fragment, p as maybeRenderHead } from "./server_DZ0K03Gt.mjs";
//#region node_modules/astro/dist/runtime/server/astro-component.js
function validateArgs(args) {
	if (args.length !== 3) return false;
	if (!args[0] || typeof args[0] !== "object") return false;
	return true;
}
function baseCreateComponent(cb, moduleId, propagation) {
	const name = moduleId?.split("/").pop()?.replace(".astro", "") ?? "";
	const fn = (...args) => {
		if (!validateArgs(args)) throw new AstroError({
			...InvalidComponentArgs,
			message: InvalidComponentArgs.message(name)
		});
		return cb(...args);
	};
	Object.defineProperty(fn, "name", {
		value: name,
		writable: false
	});
	fn.isAstroComponentFactory = true;
	fn.moduleId = moduleId;
	fn.propagation = propagation;
	return fn;
}
function createComponentWithOptions(opts) {
	return baseCreateComponent(opts.factory, opts.moduleId, opts.propagation);
}
function createComponent(arg1, moduleId, propagation) {
	if (typeof arg1 === "function") return baseCreateComponent(arg1, moduleId, propagation);
	else return createComponentWithOptions(arg1);
}
//#endregion
//#region src/components/LangNav.astro
createAstro("https://tr.codefixcoffee.com");
var $$LangNav = createComponent(($$result, $$props, $$slots) => {
	const Astro = $$result.createAstro($$props, $$slots);
	Astro.self = $$LangNav;
	const current = "tr";
	const { path } = Astro.props;
	const SITES = {
		en: {
			url: "https://codefixcoffee.com",
			native: "English"
		},
		fr: {
			url: "https://fr.codefixcoffee.com",
			native: "Français"
		},
		de: {
			url: "https://de.codefixcoffee.com",
			native: "Deutsch"
		},
		es: {
			url: "https://es.codefixcoffee.com",
			native: "Español"
		},
		it: {
			url: "https://it.codefixcoffee.com",
			native: "Italiano"
		},
		pl: {
			url: "https://pl.codefixcoffee.com",
			native: "Polski"
		},
		nl: {
			url: "https://nl.codefixcoffee.com",
			native: "Nederlands"
		},
		pt: {
			url: "https://pt.codefixcoffee.com",
			native: "Português"
		},
		uk: {
			url: "https://uk.codefixcoffee.com",
			native: "English (UK)"
		},
		au: {
			url: "https://au.codefixcoffee.com",
			native: "English (AU)"
		}
	};
	const available = Object.keys(SITES);
	const hrefFor = (loc) => {
		const base = SITES[loc].url;
		if (loc === current) return base + path;
		return base + path;
	};
	const alternates = available.map((loc) => ({
		loc,
		href: hrefFor(loc)
	}));
	return renderTemplate`${alternates.length > 1 && renderTemplate`${maybeRenderHead($$result)}<nav class="langnav" aria-label="Language"><details><summary aria-haspopup="true">${SITES[current].native} ▾</summary><ul>${alternates.map((a) => renderTemplate`<li><a${addAttribute(a.href, "href")}${addAttribute(a.loc, "hreflang")} rel="alternate"${addAttribute(a.href, "href")}>${SITES[a.loc].native}</a></li>`)}</ul></details></nav>`}<script>
// Language defaulting (browser language first, then timezone; never IP).
// - Explicit switcher choice wins forever (localStorage + cookie shared across subdomains).
// - EN master only: first visit redirects (location.replace, back-button safe) to the
//   local language; afterwards only a dismissible banner shows — never a bounce loop.
// - Crawlers (US, en, US timezone) never trigger it; hreflang equity stays intact.
(function () {
  try {
    var SITES = { en: 'https://codefixcoffee.com', fr: 'https://fr.codefixcoffee.com', de: 'https://de.codefixcoffee.com', es: 'https://es.codefixcoffee.com', it: 'https://it.codefixcoffee.com', pl: 'https://pl.codefixcoffee.com', nl: 'https://nl.codefixcoffee.com', pt: 'https://pt.codefixcoffee.com' };
    var NATIVE = { fr: 'Français', de: 'Deutsch', es: 'Español', it: 'Italiano', pl: 'Polski', nl: 'Nederlands', pt: 'Português' };
    var HERE = document.documentElement.getAttribute('data-locale') || 'en';

    // Record an explicit language choice made in the switcher on ANY locale site.
    document.addEventListener('click', function (ev) {
      var el = ev.target;
      var a = el && el.closest ? el.closest('.langnav a') : null;
      if (!a) return;
      var loc = a.getAttribute('hreflang');
      if (!loc) return;
      try { localStorage.setItem('langchoice', loc); } catch (e) {}
      try { document.cookie = 'langchoice=' + loc + ';path=/;max-age=31536000;domain=.codefixcoffee.com;SameSite=Lax'; } catch (e) {}
    }, true);

    if (HERE !== 'en') return; // auto-defaulting only originates from the EN master

    // An explicit choice anywhere on the domain suppresses auto-defaulting.
    try { if (localStorage.getItem('langchoice')) return; } catch (e) {}
    if (/(?:^|;\\s*)langchoice=[^;]/.test(document.cookie || '')) return;

    var wanted = (navigator.languages || [navigator.language || '']).map(function (l) { return (l || '').split('-')[0].toLowerCase(); });
    var primary = wanted[0] || '';
    var strong = (['de','fr','es','it','pl','nl','pt'].indexOf(primary) >= 0) ? primary : null; // e.g. a German browser anywhere
    // Timezone fallback: Switzerland → German (English-first browsers of residents in CH).
    var tzPick = null;
    try { if ((Intl.DateTimeFormat().resolvedOptions().timeZone || '') === 'Europe/Zurich') tzPick = 'de'; } catch (e) {}
    // Weaker signal: de/fr present but not first preference → banner only, no redirect.
    var weak = null;
    for (var i = 1; i < wanted.length && !weak; i++) { if (['de','fr','es','it','pl','nl','pt'].indexOf(wanted[i]) >= 0) weak = wanted[i]; }
    var redirectTarget = strong || tzPick;
    var bannerTarget = weak || tzPick;
    if (!redirectTarget && !bannerTarget) return;

    var dismissed = 'langsuggest.' + (redirectTarget || bannerTarget);
    try { if (localStorage.getItem(dismissed)) return; } catch (e) {}

    if (redirectTarget) {
      var autoKey = 'langauto.' + redirectTarget;
      var already = false;
      try { already = !!localStorage.getItem(autoKey); } catch (e) {}
      if (!already) {
        try { localStorage.setItem(autoKey, '1'); } catch (e) {}
        location.replace(SITES[redirectTarget] + location.pathname);
        return;
      }
    }

    var target = redirectTarget || bannerTarget;
    var key = 'langsuggest.' + target;
    var bar = document.createElement('div');
    bar.className = 'langbar';
    var a = document.createElement('a');
    a.href = SITES[target] + location.pathname;
    a.textContent = NATIVE[target] + ' →';
    var x = document.createElement('button');
    x.textContent = '✕';
    x.setAttribute('aria-label', 'dismiss');
    x.onclick = function () { try { localStorage.setItem(key, '1'); } catch (e) {} bar.remove(); };
    bar.appendChild(a); bar.appendChild(x);
    document.body.appendChild(bar);
  } catch (e) {}
})();
<\/script>`;
}, "/Users/kinsey/niche-site-tr/src/components/LangNav.astro", void 0);
//#endregion
//#region src/components/AdSlot.astro
createAstro("https://tr.codefixcoffee.com");
var $$AdSlot = createComponent(($$result, $$props, $$slots) => {
	const Astro = $$result.createAstro($$props, $$slots);
	Astro.self = $$AdSlot;
	const { slot = SITE.adSlotInContent } = Astro.props;
	return renderTemplate`${SITE.adsenseClient && slot && renderTemplate`${maybeRenderHead($$result)}<div class="ad"><ins class="adsbygoogle" style="display:block"${addAttribute(SITE.adsenseClient, "data-ad-client")}${addAttribute(slot, "data-ad-slot")} data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});<\/script></div>`}`;
}, "/Users/kinsey/niche-site-tr/src/components/AdSlot.astro", void 0);
//#endregion
//#region src/layouts/Base.astro
createAstro("https://tr.codefixcoffee.com");
var $$Base = createComponent(($$result, $$props, $$slots) => {
	const Astro = $$result.createAstro($$props, $$slots);
	Astro.self = $$Base;
	const { title, description, jsonLd = [], crumbs = [] } = Astro.props;
	const canonical = new URL(Astro.url.pathname, Astro.site);
	const siteUrl = Astro.site?.toString() ?? "https://codefixcoffee.com/";
	const websiteLd = {
		"@context": "https://schema.org",
		"@type": "WebSite",
		name: "CodeFix",
		alternateName: ["CodeFix Coffee", "codefixcoffee.com"],
		url: siteUrl,
		description: "Look up espresso machine and appliance error codes, with the fix first."
	};
	const organizationLd = {
		"@context": "https://schema.org",
		"@type": "Organization",
		name: "CodeFix",
		url: siteUrl,
		description: "Independent reference for appliance error codes and repairs."
	};
	const breadcrumbLd = crumbs.length ? {
		"@context": "https://schema.org",
		"@type": "BreadcrumbList",
		itemListElement: crumbs.map((c, i) => ({
			"@type": "ListItem",
			position: i + 1,
			name: c.name,
			item: new URL(c.href, Astro.site).toString()
		}))
	} : null;
	const allLd = [
		websiteLd,
		organizationLd,
		...jsonLd,
		...breadcrumbLd ? [breadcrumbLd] : []
	];
	const __path = canonical.pathname;
	const __man = {
		"fr": [
			"/",
			"/about/",
			"/breville/",
			"/breville/barista-touch-bes880/",
			"/breville/barista-touch-bes880/er01/",
			"/breville/barista-touch-bes880/er02/",
			"/breville/barista-touch-bes880/er03/",
			"/breville/barista-touch-bes880/er04/",
			"/breville/barista-touch-bes880/er05/",
			"/breville/barista-touch-bes880/er06/",
			"/breville/barista-touch-bes880/er07/",
			"/breville/barista-touch-bes880/er08/",
			"/breville/barista-touch-bes880/er09/",
			"/breville/barista-touch-bes880/er10/",
			"/breville/barista-touch-bes880/er11/",
			"/breville/barista-touch-bes880/er12/",
			"/breville/barista-touch-bes880/er13/",
			"/breville/barista-touch-bes880/er14/",
			"/breville/barista-touch-bes880/er15/",
			"/breville/barista-touch-bes880/er16/",
			"/breville/barista-touch-bes880/er17/",
			"/breville/barista-touch-bes880/er18/",
			"/breville/barista-touch-impress-bes881/",
			"/breville/barista-touch-impress-bes881/er01/",
			"/breville/barista-touch-impress-bes881/er02/",
			"/breville/barista-touch-impress-bes881/er03/",
			"/breville/barista-touch-impress-bes881/er04/",
			"/breville/barista-touch-impress-bes881/er05/",
			"/breville/barista-touch-impress-bes881/er06/",
			"/breville/barista-touch-impress-bes881/er07/",
			"/breville/barista-touch-impress-bes881/er08/",
			"/breville/barista-touch-impress-bes881/er09/",
			"/breville/barista-touch-impress-bes881/er10/",
			"/breville/barista-touch-impress-bes881/er11/",
			"/breville/barista-touch-impress-bes881/er12/",
			"/breville/barista-touch-impress-bes881/er13/",
			"/breville/barista-touch-impress-bes881/er14/",
			"/breville/barista-touch-impress-bes881/er15/",
			"/breville/barista-touch-impress-bes881/er16/",
			"/breville/barista-touch-impress-bes881/er17/",
			"/breville/barista-touch-impress-bes881/er18/",
			"/breville/dual-boiler-bes920/",
			"/breville/dual-boiler-bes920/00/",
			"/breville/dual-boiler-bes920/01/",
			"/breville/dual-boiler-bes920/02/",
			"/breville/dual-boiler-bes920/03/",
			"/breville/dual-boiler-bes920/04/",
			"/breville/dual-boiler-bes920/05/",
			"/breville/dual-boiler-bes920/06/",
			"/breville/dual-boiler-bes920/07/",
			"/breville/dual-boiler-bes920/08/",
			"/breville/dual-boiler-bes920/09/",
			"/breville/dual-boiler-bes920/10/",
			"/breville/dual-boiler-bes920/11/",
			"/breville/dual-boiler-bes920/12/",
			"/breville/oracle-bes980/",
			"/breville/oracle-bes980/error-1/",
			"/breville/oracle-bes980/error-10/",
			"/breville/oracle-bes980/error-11/",
			"/breville/oracle-bes980/error-12/",
			"/breville/oracle-bes980/error-13/",
			"/breville/oracle-bes980/error-14/",
			"/breville/oracle-bes980/error-15/",
			"/breville/oracle-bes980/error-16/",
			"/breville/oracle-bes980/error-17/",
			"/breville/oracle-bes980/error-18/",
			"/breville/oracle-bes980/error-19/",
			"/breville/oracle-bes980/error-2/",
			"/breville/oracle-bes980/error-20/",
			"/breville/oracle-bes980/error-21/",
			"/breville/oracle-bes980/error-22/",
			"/breville/oracle-bes980/error-23/",
			"/breville/oracle-bes980/error-24/",
			"/breville/oracle-bes980/error-25/",
			"/breville/oracle-bes980/error-26/",
			"/breville/oracle-bes980/error-27/",
			"/breville/oracle-bes980/error-28/",
			"/breville/oracle-bes980/error-29/",
			"/breville/oracle-bes980/error-3/",
			"/breville/oracle-bes980/error-30/",
			"/breville/oracle-bes980/error-31/",
			"/breville/oracle-bes980/error-32/",
			"/breville/oracle-bes980/error-4/",
			"/breville/oracle-bes980/error-5/",
			"/breville/oracle-bes980/error-6/",
			"/breville/oracle-bes980/error-7/",
			"/breville/oracle-bes980/error-8/",
			"/breville/oracle-bes980/error-9/",
			"/breville/oracle-jet-bes985/",
			"/breville/oracle-jet-bes985/e1/",
			"/breville/oracle-jet-bes985/e10/",
			"/breville/oracle-jet-bes985/e11/",
			"/breville/oracle-jet-bes985/e12/",
			"/breville/oracle-jet-bes985/e13/",
			"/breville/oracle-jet-bes985/e14/",
			"/breville/oracle-jet-bes985/e15/",
			"/breville/oracle-jet-bes985/e16/",
			"/breville/oracle-jet-bes985/e17/",
			"/breville/oracle-jet-bes985/e18/",
			"/breville/oracle-jet-bes985/e19/",
			"/breville/oracle-jet-bes985/e2/",
			"/breville/oracle-jet-bes985/e3/",
			"/breville/oracle-jet-bes985/e4/",
			"/breville/oracle-jet-bes985/e5/",
			"/breville/oracle-jet-bes985/e6/",
			"/breville/oracle-jet-bes985/e7/",
			"/breville/oracle-jet-bes985/e8/",
			"/breville/oracle-jet-bes985/e9/",
			"/breville/oracle-touch-bes990/",
			"/breville/oracle-touch-bes990/er01/",
			"/breville/oracle-touch-bes990/er02/",
			"/breville/oracle-touch-bes990/er03/",
			"/breville/oracle-touch-bes990/er04/",
			"/breville/oracle-touch-bes990/er05/",
			"/breville/oracle-touch-bes990/er06/",
			"/breville/oracle-touch-bes990/er07/",
			"/breville/oracle-touch-bes990/er08/",
			"/breville/oracle-touch-bes990/er09/",
			"/breville/oracle-touch-bes990/er10/",
			"/breville/oracle-touch-bes990/er11/",
			"/breville/oracle-touch-bes990/er12/",
			"/breville/oracle-touch-bes990/er13/",
			"/breville/oracle-touch-bes990/er14/",
			"/breville/oracle-touch-bes990/er15/",
			"/breville/oracle-touch-bes990/er16/",
			"/breville/oracle-touch-bes990/er17/",
			"/breville/oracle-touch-bes990/er18/",
			"/breville/oracle-touch-bes990/er19/",
			"/breville/oracle-touch-bes990/er20/",
			"/breville/oracle-touch-bes990/er21/",
			"/breville/oracle-touch-bes990/er22/",
			"/breville/oracle-touch-bes990/er23/",
			"/breville/oracle-touch-bes990/er24/",
			"/breville/oracle-touch-bes990/er25/",
			"/breville/oracle-touch-bes990/er26/",
			"/breville/oracle-touch-bes990/er27/",
			"/breville/oracle-touch-bes990/er28/",
			"/breville/oracle-touch-bes990/er29/",
			"/breville/oracle-touch-bes990/er30/",
			"/breville/oracle-touch-bes990/er31/",
			"/breville/oracle-touch-bes990/er32/",
			"/contact/",
			"/delonghi/",
			"/delonghi/magnifica-dinamica/",
			"/delonghi/magnifica-dinamica/descale-light-stays-on-after-descaling/",
			"/delonghi/magnifica-dinamica/general-alarm-code-1101-1512/",
			"/delonghi/magnifica-dinamica/grinder-stuck-code-1454/",
			"/delonghi/magnifica-dinamica/ground-too-fine-adjust-mill/",
			"/delonghi/magnifica-dinamica/insert-grounds-container-empty-grounds-container/",
			"/delonghi/magnifica-dinamica/insert-infuser-assembly/",
			"/delonghi/magnifica-dinamica/insert-water-spout/",
			"/delonghi/magnifica-dinamica/leak-alarm-code-3963/",
			"/delonghi/magnifica-dinamica/water-circuit-empty-fill-circuit/",
			"/ge/",
			"/ge/dishwasher/",
			"/ge/dishwasher/888/",
			"/ge/dishwasher/c1/",
			"/ge/dishwasher/c2/",
			"/ge/dishwasher/c3/",
			"/ge/dishwasher/c4/",
			"/ge/dishwasher/c5/",
			"/ge/dishwasher/c6/",
			"/ge/dishwasher/c7/",
			"/ge/dishwasher/c8/",
			"/ge/dishwasher/cfe/",
			"/ge/dishwasher/e1-leak/",
			"/ge/dishwasher/ftd/",
			"/ge/dishwasher/h2o/",
			"/ge/dishwasher/ih-1h/",
			"/ge/dishwasher/pf/",
			"/ge/dryer/",
			"/ge/dryer/e1/",
			"/ge/dryer/e11/",
			"/ge/dryer/e14/",
			"/ge/dryer/e3-to-e6/",
			"/ge/dryer/e4/",
			"/ge/dryer/e7/",
			"/ge/dryer/e8/",
			"/jura/",
			"/jura/automatic-machines/",
			"/jura/automatic-machines/empty-drip-tray-tray-is-empty/",
			"/jura/automatic-machines/error-1/",
			"/jura/automatic-machines/error-12/",
			"/jura/automatic-machines/error-2/",
			"/jura/automatic-machines/error-3/",
			"/jura/automatic-machines/error-4/",
			"/jura/automatic-machines/error-5/",
			"/jura/automatic-machines/error-6/",
			"/jura/automatic-machines/error-7/",
			"/jura/automatic-machines/error-8/",
			"/jura/automatic-machines/fill-water-tank-tank-is-full/",
			"/miele/",
			"/miele/cm-cva-machines/",
			"/miele/cm-cva-machines/f10-f17/",
			"/miele/cm-cva-machines/f77/",
			"/nespresso/",
			"/nespresso/vertuo-machines/",
			"/nespresso/vertuo-machines/1301-1305/",
			"/nespresso/vertuo-machines/blinking-lights/",
			"/philips-saeco/",
			"/philips-saeco/espresso-machines/",
			"/philips-saeco/espresso-machines/error-01/",
			"/philips-saeco/espresso-machines/error-02-10-15-or-22/",
			"/philips-saeco/espresso-machines/error-03/",
			"/philips-saeco/espresso-machines/error-04/",
			"/philips-saeco/espresso-machines/error-05/",
			"/philips-saeco/espresso-machines/error-11-or-19/",
			"/philips-saeco/espresso-machines/error-14/",
			"/philips-saeco/espresso-machines/error-20/",
			"/privacy/",
			"/samsung-oven-error-codes/",
			"/samsung/",
			"/samsung/range-wall-oven/",
			"/samsung/range-wall-oven/bo-bs/",
			"/samsung/range-wall-oven/c-21/",
			"/samsung/range-wall-oven/c-24/",
			"/samsung/range-wall-oven/c-d0/",
			"/samsung/range-wall-oven/c-f2/",
			"/samsung/range-wall-oven/ce-56/",
			"/samsung/range-wall-oven/e-08/",
			"/samsung/range-wall-oven/e-0a/",
			"/samsung/range-wall-oven/e-0e-fl/",
			"/samsung/range-wall-oven/e-27/",
			"/samsung/range-wall-oven/e-28/",
			"/samsung/range-wall-oven/e-54/",
			"/samsung/range-wall-oven/e-55/",
			"/samsung/range-wall-oven/le/",
			"/samsung/range-wall-oven/ot/",
			"/samsung/range-wall-oven/se/",
			"/samsung/range-wall-oven/te/",
			"/samsung/range-wall-oven/to-ts/"
		],
		"de": [
			"/",
			"/about/",
			"/breville/",
			"/breville/barista-touch-bes880/",
			"/breville/barista-touch-bes880/er01/",
			"/breville/barista-touch-bes880/er02/",
			"/breville/barista-touch-bes880/er03/",
			"/breville/barista-touch-bes880/er04/",
			"/breville/barista-touch-bes880/er05/",
			"/breville/barista-touch-bes880/er06/",
			"/breville/barista-touch-bes880/er07/",
			"/breville/barista-touch-bes880/er08/",
			"/breville/barista-touch-bes880/er09/",
			"/breville/barista-touch-bes880/er10/",
			"/breville/barista-touch-bes880/er11/",
			"/breville/barista-touch-bes880/er12/",
			"/breville/barista-touch-bes880/er13/",
			"/breville/barista-touch-bes880/er14/",
			"/breville/barista-touch-bes880/er15/",
			"/breville/barista-touch-bes880/er16/",
			"/breville/barista-touch-bes880/er17/",
			"/breville/barista-touch-bes880/er18/",
			"/breville/barista-touch-impress-bes881/",
			"/breville/barista-touch-impress-bes881/er01/",
			"/breville/barista-touch-impress-bes881/er02/",
			"/breville/barista-touch-impress-bes881/er03/",
			"/breville/barista-touch-impress-bes881/er04/",
			"/breville/barista-touch-impress-bes881/er05/",
			"/breville/barista-touch-impress-bes881/er06/",
			"/breville/barista-touch-impress-bes881/er07/",
			"/breville/barista-touch-impress-bes881/er08/",
			"/breville/barista-touch-impress-bes881/er09/",
			"/breville/barista-touch-impress-bes881/er10/",
			"/breville/barista-touch-impress-bes881/er11/",
			"/breville/barista-touch-impress-bes881/er12/",
			"/breville/barista-touch-impress-bes881/er13/",
			"/breville/barista-touch-impress-bes881/er14/",
			"/breville/barista-touch-impress-bes881/er15/",
			"/breville/barista-touch-impress-bes881/er16/",
			"/breville/barista-touch-impress-bes881/er17/",
			"/breville/barista-touch-impress-bes881/er18/",
			"/breville/dual-boiler-bes920/",
			"/breville/dual-boiler-bes920/00/",
			"/breville/dual-boiler-bes920/01/",
			"/breville/dual-boiler-bes920/02/",
			"/breville/dual-boiler-bes920/03/",
			"/breville/dual-boiler-bes920/04/",
			"/breville/dual-boiler-bes920/05/",
			"/breville/dual-boiler-bes920/06/",
			"/breville/dual-boiler-bes920/07/",
			"/breville/dual-boiler-bes920/08/",
			"/breville/dual-boiler-bes920/09/",
			"/breville/dual-boiler-bes920/10/",
			"/breville/dual-boiler-bes920/11/",
			"/breville/dual-boiler-bes920/12/",
			"/breville/oracle-bes980/",
			"/breville/oracle-bes980/error-1/",
			"/breville/oracle-bes980/error-10/",
			"/breville/oracle-bes980/error-11/",
			"/breville/oracle-bes980/error-12/",
			"/breville/oracle-bes980/error-13/",
			"/breville/oracle-bes980/error-14/",
			"/breville/oracle-bes980/error-15/",
			"/breville/oracle-bes980/error-16/",
			"/breville/oracle-bes980/error-17/",
			"/breville/oracle-bes980/error-18/",
			"/breville/oracle-bes980/error-19/",
			"/breville/oracle-bes980/error-2/",
			"/breville/oracle-bes980/error-20/",
			"/breville/oracle-bes980/error-21/",
			"/breville/oracle-bes980/error-22/",
			"/breville/oracle-bes980/error-23/",
			"/breville/oracle-bes980/error-24/",
			"/breville/oracle-bes980/error-25/",
			"/breville/oracle-bes980/error-26/",
			"/breville/oracle-bes980/error-27/",
			"/breville/oracle-bes980/error-28/",
			"/breville/oracle-bes980/error-29/",
			"/breville/oracle-bes980/error-3/",
			"/breville/oracle-bes980/error-30/",
			"/breville/oracle-bes980/error-31/",
			"/breville/oracle-bes980/error-32/",
			"/breville/oracle-bes980/error-4/",
			"/breville/oracle-bes980/error-5/",
			"/breville/oracle-bes980/error-6/",
			"/breville/oracle-bes980/error-7/",
			"/breville/oracle-bes980/error-8/",
			"/breville/oracle-bes980/error-9/",
			"/breville/oracle-jet-bes985/",
			"/breville/oracle-jet-bes985/e1/",
			"/breville/oracle-jet-bes985/e10/",
			"/breville/oracle-jet-bes985/e11/",
			"/breville/oracle-jet-bes985/e12/",
			"/breville/oracle-jet-bes985/e13/",
			"/breville/oracle-jet-bes985/e14/",
			"/breville/oracle-jet-bes985/e15/",
			"/breville/oracle-jet-bes985/e16/",
			"/breville/oracle-jet-bes985/e17/",
			"/breville/oracle-jet-bes985/e18/",
			"/breville/oracle-jet-bes985/e19/",
			"/breville/oracle-jet-bes985/e2/",
			"/breville/oracle-jet-bes985/e3/",
			"/breville/oracle-jet-bes985/e4/",
			"/breville/oracle-jet-bes985/e5/",
			"/breville/oracle-jet-bes985/e6/",
			"/breville/oracle-jet-bes985/e7/",
			"/breville/oracle-jet-bes985/e8/",
			"/breville/oracle-jet-bes985/e9/",
			"/breville/oracle-touch-bes990/",
			"/breville/oracle-touch-bes990/er01/",
			"/breville/oracle-touch-bes990/er02/",
			"/breville/oracle-touch-bes990/er03/",
			"/breville/oracle-touch-bes990/er04/",
			"/breville/oracle-touch-bes990/er05/",
			"/breville/oracle-touch-bes990/er06/",
			"/breville/oracle-touch-bes990/er07/",
			"/breville/oracle-touch-bes990/er08/",
			"/breville/oracle-touch-bes990/er09/",
			"/breville/oracle-touch-bes990/er10/",
			"/breville/oracle-touch-bes990/er11/",
			"/breville/oracle-touch-bes990/er12/",
			"/breville/oracle-touch-bes990/er13/",
			"/breville/oracle-touch-bes990/er14/",
			"/breville/oracle-touch-bes990/er15/",
			"/breville/oracle-touch-bes990/er16/",
			"/breville/oracle-touch-bes990/er17/",
			"/breville/oracle-touch-bes990/er18/",
			"/breville/oracle-touch-bes990/er19/",
			"/breville/oracle-touch-bes990/er20/",
			"/breville/oracle-touch-bes990/er21/",
			"/breville/oracle-touch-bes990/er22/",
			"/breville/oracle-touch-bes990/er23/",
			"/breville/oracle-touch-bes990/er24/",
			"/breville/oracle-touch-bes990/er25/",
			"/breville/oracle-touch-bes990/er26/",
			"/breville/oracle-touch-bes990/er27/",
			"/breville/oracle-touch-bes990/er28/",
			"/breville/oracle-touch-bes990/er29/",
			"/breville/oracle-touch-bes990/er30/",
			"/breville/oracle-touch-bes990/er31/",
			"/breville/oracle-touch-bes990/er32/",
			"/contact/",
			"/delonghi/",
			"/delonghi/magnifica-dinamica/",
			"/delonghi/magnifica-dinamica/descale-light-stays-on-after-descaling/",
			"/delonghi/magnifica-dinamica/general-alarm-code-1101-1512/",
			"/delonghi/magnifica-dinamica/grinder-stuck-code-1454/",
			"/delonghi/magnifica-dinamica/ground-too-fine-adjust-mill/",
			"/delonghi/magnifica-dinamica/insert-grounds-container-empty-grounds-container/",
			"/delonghi/magnifica-dinamica/insert-infuser-assembly/",
			"/delonghi/magnifica-dinamica/insert-water-spout/",
			"/delonghi/magnifica-dinamica/leak-alarm-code-3963/",
			"/delonghi/magnifica-dinamica/water-circuit-empty-fill-circuit/",
			"/ge/",
			"/ge/dishwasher/",
			"/ge/dishwasher/888/",
			"/ge/dishwasher/c1/",
			"/ge/dishwasher/c2/",
			"/ge/dishwasher/c3/",
			"/ge/dishwasher/c4/",
			"/ge/dishwasher/c5/",
			"/ge/dishwasher/c6/",
			"/ge/dishwasher/c7/",
			"/ge/dishwasher/c8/",
			"/ge/dishwasher/cfe/",
			"/ge/dishwasher/e1-leak/",
			"/ge/dishwasher/ftd/",
			"/ge/dishwasher/h2o/",
			"/ge/dishwasher/ih-1h/",
			"/ge/dishwasher/pf/",
			"/ge/dryer/",
			"/ge/dryer/e1/",
			"/ge/dryer/e11/",
			"/ge/dryer/e14/",
			"/ge/dryer/e3-to-e6/",
			"/ge/dryer/e4/",
			"/ge/dryer/e7/",
			"/ge/dryer/e8/",
			"/jura/",
			"/jura/automatic-machines/",
			"/jura/automatic-machines/empty-drip-tray-tray-is-empty/",
			"/jura/automatic-machines/error-1/",
			"/jura/automatic-machines/error-12/",
			"/jura/automatic-machines/error-2/",
			"/jura/automatic-machines/error-3/",
			"/jura/automatic-machines/error-4/",
			"/jura/automatic-machines/error-5/",
			"/jura/automatic-machines/error-6/",
			"/jura/automatic-machines/error-7/",
			"/jura/automatic-machines/error-8/",
			"/jura/automatic-machines/fill-water-tank-tank-is-full/",
			"/miele/",
			"/miele/cm-cva-machines/",
			"/miele/cm-cva-machines/f10-f17/",
			"/miele/cm-cva-machines/f77/",
			"/nespresso/",
			"/nespresso/vertuo-machines/",
			"/nespresso/vertuo-machines/1301-1305/",
			"/nespresso/vertuo-machines/blinking-lights/",
			"/philips-saeco/",
			"/philips-saeco/espresso-machines/",
			"/philips-saeco/espresso-machines/error-01/",
			"/philips-saeco/espresso-machines/error-02-10-15-or-22/",
			"/philips-saeco/espresso-machines/error-03/",
			"/philips-saeco/espresso-machines/error-04/",
			"/philips-saeco/espresso-machines/error-05/",
			"/philips-saeco/espresso-machines/error-11-or-19/",
			"/philips-saeco/espresso-machines/error-14/",
			"/philips-saeco/espresso-machines/error-20/",
			"/privacy/",
			"/samsung-oven-error-codes/",
			"/samsung/",
			"/samsung/range-wall-oven/",
			"/samsung/range-wall-oven/bo-bs/",
			"/samsung/range-wall-oven/c-21/",
			"/samsung/range-wall-oven/c-24/",
			"/samsung/range-wall-oven/c-d0/",
			"/samsung/range-wall-oven/c-f2/",
			"/samsung/range-wall-oven/ce-56/",
			"/samsung/range-wall-oven/e-08/",
			"/samsung/range-wall-oven/e-0a/",
			"/samsung/range-wall-oven/e-0e-fl/",
			"/samsung/range-wall-oven/e-27/",
			"/samsung/range-wall-oven/e-28/",
			"/samsung/range-wall-oven/e-54/",
			"/samsung/range-wall-oven/e-55/",
			"/samsung/range-wall-oven/le/",
			"/samsung/range-wall-oven/ot/",
			"/samsung/range-wall-oven/se/",
			"/samsung/range-wall-oven/te/",
			"/samsung/range-wall-oven/to-ts/"
		],
		"uk": [
			"/",
			"/about/",
			"/breville/",
			"/breville/barista-touch-bes880/",
			"/breville/barista-touch-bes880/er01/",
			"/breville/barista-touch-bes880/er02/",
			"/breville/barista-touch-bes880/er03/",
			"/breville/barista-touch-bes880/er04/",
			"/breville/barista-touch-bes880/er05/",
			"/breville/barista-touch-bes880/er06/",
			"/breville/barista-touch-bes880/er07/",
			"/breville/barista-touch-bes880/er08/",
			"/breville/barista-touch-bes880/er09/",
			"/breville/barista-touch-bes880/er10/",
			"/breville/barista-touch-bes880/er11/",
			"/breville/barista-touch-bes880/er12/",
			"/breville/barista-touch-bes880/er13/",
			"/breville/barista-touch-bes880/er14/",
			"/breville/barista-touch-bes880/er15/",
			"/breville/barista-touch-bes880/er16/",
			"/breville/barista-touch-bes880/er17/",
			"/breville/barista-touch-bes880/er18/",
			"/breville/barista-touch-impress-bes881/",
			"/breville/barista-touch-impress-bes881/er01/",
			"/breville/barista-touch-impress-bes881/er02/",
			"/breville/barista-touch-impress-bes881/er03/",
			"/breville/barista-touch-impress-bes881/er04/",
			"/breville/barista-touch-impress-bes881/er05/",
			"/breville/barista-touch-impress-bes881/er06/",
			"/breville/barista-touch-impress-bes881/er07/",
			"/breville/barista-touch-impress-bes881/er08/",
			"/breville/barista-touch-impress-bes881/er09/",
			"/breville/barista-touch-impress-bes881/er10/",
			"/breville/barista-touch-impress-bes881/er11/",
			"/breville/barista-touch-impress-bes881/er12/",
			"/breville/barista-touch-impress-bes881/er13/",
			"/breville/barista-touch-impress-bes881/er14/",
			"/breville/barista-touch-impress-bes881/er15/",
			"/breville/barista-touch-impress-bes881/er16/",
			"/breville/barista-touch-impress-bes881/er17/",
			"/breville/barista-touch-impress-bes881/er18/",
			"/breville/dual-boiler-bes920/",
			"/breville/dual-boiler-bes920/00/",
			"/breville/dual-boiler-bes920/01/",
			"/breville/dual-boiler-bes920/02/",
			"/breville/dual-boiler-bes920/03/",
			"/breville/dual-boiler-bes920/04/",
			"/breville/dual-boiler-bes920/05/",
			"/breville/dual-boiler-bes920/06/",
			"/breville/dual-boiler-bes920/07/",
			"/breville/dual-boiler-bes920/08/",
			"/breville/dual-boiler-bes920/09/",
			"/breville/dual-boiler-bes920/10/",
			"/breville/dual-boiler-bes920/11/",
			"/breville/dual-boiler-bes920/12/",
			"/breville/oracle-bes980/",
			"/breville/oracle-bes980/error-1/",
			"/breville/oracle-bes980/error-10/",
			"/breville/oracle-bes980/error-11/",
			"/breville/oracle-bes980/error-12/",
			"/breville/oracle-bes980/error-13/",
			"/breville/oracle-bes980/error-14/",
			"/breville/oracle-bes980/error-15/",
			"/breville/oracle-bes980/error-16/",
			"/breville/oracle-bes980/error-17/",
			"/breville/oracle-bes980/error-18/",
			"/breville/oracle-bes980/error-19/",
			"/breville/oracle-bes980/error-2/",
			"/breville/oracle-bes980/error-20/",
			"/breville/oracle-bes980/error-21/",
			"/breville/oracle-bes980/error-22/",
			"/breville/oracle-bes980/error-23/",
			"/breville/oracle-bes980/error-24/",
			"/breville/oracle-bes980/error-25/",
			"/breville/oracle-bes980/error-26/",
			"/breville/oracle-bes980/error-27/",
			"/breville/oracle-bes980/error-28/",
			"/breville/oracle-bes980/error-29/",
			"/breville/oracle-bes980/error-3/",
			"/breville/oracle-bes980/error-30/",
			"/breville/oracle-bes980/error-31/",
			"/breville/oracle-bes980/error-32/",
			"/breville/oracle-bes980/error-4/",
			"/breville/oracle-bes980/error-5/",
			"/breville/oracle-bes980/error-6/",
			"/breville/oracle-bes980/error-7/",
			"/breville/oracle-bes980/error-8/",
			"/breville/oracle-bes980/error-9/",
			"/breville/oracle-jet-bes985/",
			"/breville/oracle-jet-bes985/e1/",
			"/breville/oracle-jet-bes985/e10/",
			"/breville/oracle-jet-bes985/e11/",
			"/breville/oracle-jet-bes985/e12/",
			"/breville/oracle-jet-bes985/e13/",
			"/breville/oracle-jet-bes985/e14/",
			"/breville/oracle-jet-bes985/e15/",
			"/breville/oracle-jet-bes985/e16/",
			"/breville/oracle-jet-bes985/e17/",
			"/breville/oracle-jet-bes985/e18/",
			"/breville/oracle-jet-bes985/e19/",
			"/breville/oracle-jet-bes985/e2/",
			"/breville/oracle-jet-bes985/e3/",
			"/breville/oracle-jet-bes985/e4/",
			"/breville/oracle-jet-bes985/e5/",
			"/breville/oracle-jet-bes985/e6/",
			"/breville/oracle-jet-bes985/e7/",
			"/breville/oracle-jet-bes985/e8/",
			"/breville/oracle-jet-bes985/e9/",
			"/breville/oracle-touch-bes990/",
			"/breville/oracle-touch-bes990/er01/",
			"/breville/oracle-touch-bes990/er02/",
			"/breville/oracle-touch-bes990/er03/",
			"/breville/oracle-touch-bes990/er04/",
			"/breville/oracle-touch-bes990/er05/",
			"/breville/oracle-touch-bes990/er06/",
			"/breville/oracle-touch-bes990/er07/",
			"/breville/oracle-touch-bes990/er08/",
			"/breville/oracle-touch-bes990/er09/",
			"/breville/oracle-touch-bes990/er10/",
			"/breville/oracle-touch-bes990/er11/",
			"/breville/oracle-touch-bes990/er12/",
			"/breville/oracle-touch-bes990/er13/",
			"/breville/oracle-touch-bes990/er14/",
			"/breville/oracle-touch-bes990/er15/",
			"/breville/oracle-touch-bes990/er16/",
			"/breville/oracle-touch-bes990/er17/",
			"/breville/oracle-touch-bes990/er18/",
			"/breville/oracle-touch-bes990/er19/",
			"/breville/oracle-touch-bes990/er20/",
			"/breville/oracle-touch-bes990/er21/",
			"/breville/oracle-touch-bes990/er22/",
			"/breville/oracle-touch-bes990/er23/",
			"/breville/oracle-touch-bes990/er24/",
			"/breville/oracle-touch-bes990/er25/",
			"/breville/oracle-touch-bes990/er26/",
			"/breville/oracle-touch-bes990/er27/",
			"/breville/oracle-touch-bes990/er28/",
			"/breville/oracle-touch-bes990/er29/",
			"/breville/oracle-touch-bes990/er30/",
			"/breville/oracle-touch-bes990/er31/",
			"/breville/oracle-touch-bes990/er32/",
			"/contact/",
			"/delonghi/",
			"/delonghi/magnifica-dinamica/",
			"/delonghi/magnifica-dinamica/descale-light-stays-on-after-descaling/",
			"/delonghi/magnifica-dinamica/general-alarm-code-1101-1512/",
			"/delonghi/magnifica-dinamica/grinder-stuck-code-1454/",
			"/delonghi/magnifica-dinamica/ground-too-fine-adjust-mill/",
			"/delonghi/magnifica-dinamica/insert-grounds-container-empty-grounds-container/",
			"/delonghi/magnifica-dinamica/insert-infuser-assembly/",
			"/delonghi/magnifica-dinamica/insert-water-spout/",
			"/delonghi/magnifica-dinamica/leak-alarm-code-3963/",
			"/delonghi/magnifica-dinamica/water-circuit-empty-fill-circuit/",
			"/ge/",
			"/ge/dishwasher/",
			"/ge/dishwasher/888/",
			"/ge/dishwasher/c1/",
			"/ge/dishwasher/c2/",
			"/ge/dishwasher/c3/",
			"/ge/dishwasher/c4/",
			"/ge/dishwasher/c5/",
			"/ge/dishwasher/c6/",
			"/ge/dishwasher/c7/",
			"/ge/dishwasher/c8/",
			"/ge/dishwasher/cfe/",
			"/ge/dishwasher/e1-leak/",
			"/ge/dishwasher/ftd/",
			"/ge/dishwasher/h2o/",
			"/ge/dishwasher/ih-1h/",
			"/ge/dishwasher/pf/",
			"/ge/dryer/",
			"/ge/dryer/e1/",
			"/ge/dryer/e11/",
			"/ge/dryer/e14/",
			"/ge/dryer/e3-to-e6/",
			"/ge/dryer/e4/",
			"/ge/dryer/e7/",
			"/ge/dryer/e8/",
			"/jura/",
			"/jura/automatic-machines/",
			"/jura/automatic-machines/empty-drip-tray-tray-is-empty/",
			"/jura/automatic-machines/error-1/",
			"/jura/automatic-machines/error-12/",
			"/jura/automatic-machines/error-2/",
			"/jura/automatic-machines/error-3/",
			"/jura/automatic-machines/error-4/",
			"/jura/automatic-machines/error-5/",
			"/jura/automatic-machines/error-6/",
			"/jura/automatic-machines/error-7/",
			"/jura/automatic-machines/error-8/",
			"/jura/automatic-machines/fill-water-tank-tank-is-full/",
			"/miele/",
			"/miele/cm-cva-machines/",
			"/miele/cm-cva-machines/f10-f17/",
			"/miele/cm-cva-machines/f77/",
			"/nespresso/",
			"/nespresso/vertuo-machines/",
			"/nespresso/vertuo-machines/1301-1305/",
			"/nespresso/vertuo-machines/blinking-lights/",
			"/philips-saeco/",
			"/philips-saeco/espresso-machines/",
			"/philips-saeco/espresso-machines/error-01/",
			"/philips-saeco/espresso-machines/error-02-10-15-or-22/",
			"/philips-saeco/espresso-machines/error-03/",
			"/philips-saeco/espresso-machines/error-04/",
			"/philips-saeco/espresso-machines/error-05/",
			"/philips-saeco/espresso-machines/error-11-or-19/",
			"/philips-saeco/espresso-machines/error-14/",
			"/philips-saeco/espresso-machines/error-20/",
			"/privacy/",
			"/samsung-oven-error-codes/",
			"/samsung/",
			"/samsung/range-wall-oven/",
			"/samsung/range-wall-oven/bo-bs/",
			"/samsung/range-wall-oven/c-21/",
			"/samsung/range-wall-oven/c-24/",
			"/samsung/range-wall-oven/c-d0/",
			"/samsung/range-wall-oven/c-f2/",
			"/samsung/range-wall-oven/ce-56/",
			"/samsung/range-wall-oven/e-08/",
			"/samsung/range-wall-oven/e-0a/",
			"/samsung/range-wall-oven/e-0e-fl/",
			"/samsung/range-wall-oven/e-27/",
			"/samsung/range-wall-oven/e-28/",
			"/samsung/range-wall-oven/e-54/",
			"/samsung/range-wall-oven/e-55/",
			"/samsung/range-wall-oven/le/",
			"/samsung/range-wall-oven/ot/",
			"/samsung/range-wall-oven/se/",
			"/samsung/range-wall-oven/te/",
			"/samsung/range-wall-oven/to-ts/"
		],
		"au": [
			"/",
			"/about/",
			"/breville/",
			"/breville/barista-touch-bes880/",
			"/breville/barista-touch-bes880/er01/",
			"/breville/barista-touch-bes880/er02/",
			"/breville/barista-touch-bes880/er03/",
			"/breville/barista-touch-bes880/er04/",
			"/breville/barista-touch-bes880/er05/",
			"/breville/barista-touch-bes880/er06/",
			"/breville/barista-touch-bes880/er07/",
			"/breville/barista-touch-bes880/er08/",
			"/breville/barista-touch-bes880/er09/",
			"/breville/barista-touch-bes880/er10/",
			"/breville/barista-touch-bes880/er11/",
			"/breville/barista-touch-bes880/er12/",
			"/breville/barista-touch-bes880/er13/",
			"/breville/barista-touch-bes880/er14/",
			"/breville/barista-touch-bes880/er15/",
			"/breville/barista-touch-bes880/er16/",
			"/breville/barista-touch-bes880/er17/",
			"/breville/barista-touch-bes880/er18/",
			"/breville/barista-touch-impress-bes881/",
			"/breville/barista-touch-impress-bes881/er01/",
			"/breville/barista-touch-impress-bes881/er02/",
			"/breville/barista-touch-impress-bes881/er03/",
			"/breville/barista-touch-impress-bes881/er04/",
			"/breville/barista-touch-impress-bes881/er05/",
			"/breville/barista-touch-impress-bes881/er06/",
			"/breville/barista-touch-impress-bes881/er07/",
			"/breville/barista-touch-impress-bes881/er08/",
			"/breville/barista-touch-impress-bes881/er09/",
			"/breville/barista-touch-impress-bes881/er10/",
			"/breville/barista-touch-impress-bes881/er11/",
			"/breville/barista-touch-impress-bes881/er12/",
			"/breville/barista-touch-impress-bes881/er13/",
			"/breville/barista-touch-impress-bes881/er14/",
			"/breville/barista-touch-impress-bes881/er15/",
			"/breville/barista-touch-impress-bes881/er16/",
			"/breville/barista-touch-impress-bes881/er17/",
			"/breville/barista-touch-impress-bes881/er18/",
			"/breville/dual-boiler-bes920/",
			"/breville/dual-boiler-bes920/00/",
			"/breville/dual-boiler-bes920/01/",
			"/breville/dual-boiler-bes920/02/",
			"/breville/dual-boiler-bes920/03/",
			"/breville/dual-boiler-bes920/04/",
			"/breville/dual-boiler-bes920/05/",
			"/breville/dual-boiler-bes920/06/",
			"/breville/dual-boiler-bes920/07/",
			"/breville/dual-boiler-bes920/08/",
			"/breville/dual-boiler-bes920/09/",
			"/breville/dual-boiler-bes920/10/",
			"/breville/dual-boiler-bes920/11/",
			"/breville/dual-boiler-bes920/12/",
			"/breville/oracle-bes980/",
			"/breville/oracle-bes980/error-1/",
			"/breville/oracle-bes980/error-10/",
			"/breville/oracle-bes980/error-11/",
			"/breville/oracle-bes980/error-12/",
			"/breville/oracle-bes980/error-13/",
			"/breville/oracle-bes980/error-14/",
			"/breville/oracle-bes980/error-15/",
			"/breville/oracle-bes980/error-16/",
			"/breville/oracle-bes980/error-17/",
			"/breville/oracle-bes980/error-18/",
			"/breville/oracle-bes980/error-19/",
			"/breville/oracle-bes980/error-2/",
			"/breville/oracle-bes980/error-20/",
			"/breville/oracle-bes980/error-21/",
			"/breville/oracle-bes980/error-22/",
			"/breville/oracle-bes980/error-23/",
			"/breville/oracle-bes980/error-24/",
			"/breville/oracle-bes980/error-25/",
			"/breville/oracle-bes980/error-26/",
			"/breville/oracle-bes980/error-27/",
			"/breville/oracle-bes980/error-28/",
			"/breville/oracle-bes980/error-29/",
			"/breville/oracle-bes980/error-3/",
			"/breville/oracle-bes980/error-30/",
			"/breville/oracle-bes980/error-31/",
			"/breville/oracle-bes980/error-32/",
			"/breville/oracle-bes980/error-4/",
			"/breville/oracle-bes980/error-5/",
			"/breville/oracle-bes980/error-6/",
			"/breville/oracle-bes980/error-7/",
			"/breville/oracle-bes980/error-8/",
			"/breville/oracle-bes980/error-9/",
			"/breville/oracle-jet-bes985/",
			"/breville/oracle-jet-bes985/e1/",
			"/breville/oracle-jet-bes985/e10/",
			"/breville/oracle-jet-bes985/e11/",
			"/breville/oracle-jet-bes985/e12/",
			"/breville/oracle-jet-bes985/e13/",
			"/breville/oracle-jet-bes985/e14/",
			"/breville/oracle-jet-bes985/e15/",
			"/breville/oracle-jet-bes985/e16/",
			"/breville/oracle-jet-bes985/e17/",
			"/breville/oracle-jet-bes985/e18/",
			"/breville/oracle-jet-bes985/e19/",
			"/breville/oracle-jet-bes985/e2/",
			"/breville/oracle-jet-bes985/e3/",
			"/breville/oracle-jet-bes985/e4/",
			"/breville/oracle-jet-bes985/e5/",
			"/breville/oracle-jet-bes985/e6/",
			"/breville/oracle-jet-bes985/e7/",
			"/breville/oracle-jet-bes985/e8/",
			"/breville/oracle-jet-bes985/e9/",
			"/breville/oracle-touch-bes990/",
			"/breville/oracle-touch-bes990/er01/",
			"/breville/oracle-touch-bes990/er02/",
			"/breville/oracle-touch-bes990/er03/",
			"/breville/oracle-touch-bes990/er04/",
			"/breville/oracle-touch-bes990/er05/",
			"/breville/oracle-touch-bes990/er06/",
			"/breville/oracle-touch-bes990/er07/",
			"/breville/oracle-touch-bes990/er08/",
			"/breville/oracle-touch-bes990/er09/",
			"/breville/oracle-touch-bes990/er10/",
			"/breville/oracle-touch-bes990/er11/",
			"/breville/oracle-touch-bes990/er12/",
			"/breville/oracle-touch-bes990/er13/",
			"/breville/oracle-touch-bes990/er14/",
			"/breville/oracle-touch-bes990/er15/",
			"/breville/oracle-touch-bes990/er16/",
			"/breville/oracle-touch-bes990/er17/",
			"/breville/oracle-touch-bes990/er18/",
			"/breville/oracle-touch-bes990/er19/",
			"/breville/oracle-touch-bes990/er20/",
			"/breville/oracle-touch-bes990/er21/",
			"/breville/oracle-touch-bes990/er22/",
			"/breville/oracle-touch-bes990/er23/",
			"/breville/oracle-touch-bes990/er24/",
			"/breville/oracle-touch-bes990/er25/",
			"/breville/oracle-touch-bes990/er26/",
			"/breville/oracle-touch-bes990/er27/",
			"/breville/oracle-touch-bes990/er28/",
			"/breville/oracle-touch-bes990/er29/",
			"/breville/oracle-touch-bes990/er30/",
			"/breville/oracle-touch-bes990/er31/",
			"/breville/oracle-touch-bes990/er32/",
			"/contact/",
			"/delonghi/",
			"/delonghi/magnifica-dinamica/",
			"/delonghi/magnifica-dinamica/descale-light-stays-on-after-descaling/",
			"/delonghi/magnifica-dinamica/general-alarm-code-1101-1512/",
			"/delonghi/magnifica-dinamica/grinder-stuck-code-1454/",
			"/delonghi/magnifica-dinamica/ground-too-fine-adjust-mill/",
			"/delonghi/magnifica-dinamica/insert-grounds-container-empty-grounds-container/",
			"/delonghi/magnifica-dinamica/insert-infuser-assembly/",
			"/delonghi/magnifica-dinamica/insert-water-spout/",
			"/delonghi/magnifica-dinamica/leak-alarm-code-3963/",
			"/delonghi/magnifica-dinamica/water-circuit-empty-fill-circuit/",
			"/ge/",
			"/ge/dishwasher/",
			"/ge/dishwasher/888/",
			"/ge/dishwasher/c1/",
			"/ge/dishwasher/c2/",
			"/ge/dishwasher/c3/",
			"/ge/dishwasher/c4/",
			"/ge/dishwasher/c5/",
			"/ge/dishwasher/c6/",
			"/ge/dishwasher/c7/",
			"/ge/dishwasher/c8/",
			"/ge/dishwasher/cfe/",
			"/ge/dishwasher/e1-leak/",
			"/ge/dishwasher/ftd/",
			"/ge/dishwasher/h2o/",
			"/ge/dishwasher/ih-1h/",
			"/ge/dishwasher/pf/",
			"/ge/dryer/",
			"/ge/dryer/e1/",
			"/ge/dryer/e11/",
			"/ge/dryer/e14/",
			"/ge/dryer/e3-to-e6/",
			"/ge/dryer/e4/",
			"/ge/dryer/e7/",
			"/ge/dryer/e8/",
			"/jura/",
			"/jura/automatic-machines/",
			"/jura/automatic-machines/empty-drip-tray-tray-is-empty/",
			"/jura/automatic-machines/error-1/",
			"/jura/automatic-machines/error-12/",
			"/jura/automatic-machines/error-2/",
			"/jura/automatic-machines/error-3/",
			"/jura/automatic-machines/error-4/",
			"/jura/automatic-machines/error-5/",
			"/jura/automatic-machines/error-6/",
			"/jura/automatic-machines/error-7/",
			"/jura/automatic-machines/error-8/",
			"/jura/automatic-machines/fill-water-tank-tank-is-full/",
			"/miele/",
			"/miele/cm-cva-machines/",
			"/miele/cm-cva-machines/f10-f17/",
			"/miele/cm-cva-machines/f77/",
			"/nespresso/",
			"/nespresso/vertuo-machines/",
			"/nespresso/vertuo-machines/1301-1305/",
			"/nespresso/vertuo-machines/blinking-lights/",
			"/philips-saeco/",
			"/philips-saeco/espresso-machines/",
			"/philips-saeco/espresso-machines/error-01/",
			"/philips-saeco/espresso-machines/error-02-10-15-or-22/",
			"/philips-saeco/espresso-machines/error-03/",
			"/philips-saeco/espresso-machines/error-04/",
			"/philips-saeco/espresso-machines/error-05/",
			"/philips-saeco/espresso-machines/error-11-or-19/",
			"/philips-saeco/espresso-machines/error-14/",
			"/philips-saeco/espresso-machines/error-20/",
			"/privacy/",
			"/samsung-oven-error-codes/",
			"/samsung/",
			"/samsung/range-wall-oven/",
			"/samsung/range-wall-oven/bo-bs/",
			"/samsung/range-wall-oven/c-21/",
			"/samsung/range-wall-oven/c-24/",
			"/samsung/range-wall-oven/c-d0/",
			"/samsung/range-wall-oven/c-f2/",
			"/samsung/range-wall-oven/ce-56/",
			"/samsung/range-wall-oven/e-08/",
			"/samsung/range-wall-oven/e-0a/",
			"/samsung/range-wall-oven/e-0e-fl/",
			"/samsung/range-wall-oven/e-27/",
			"/samsung/range-wall-oven/e-28/",
			"/samsung/range-wall-oven/e-54/",
			"/samsung/range-wall-oven/e-55/",
			"/samsung/range-wall-oven/le/",
			"/samsung/range-wall-oven/ot/",
			"/samsung/range-wall-oven/se/",
			"/samsung/range-wall-oven/te/",
			"/samsung/range-wall-oven/to-ts/"
		]
	};
	const __all = [
		["en", "https://codefixcoffee.com"],
		["fr", "https://fr.codefixcoffee.com"],
		["de", "https://de.codefixcoffee.com"],
		["es", "https://es.codefixcoffee.com"],
		["it", "https://it.codefixcoffee.com"],
		["pl", "https://pl.codefixcoffee.com"],
		["nl", "https://nl.codefixcoffee.com"],
		["pt", "https://pt.codefixcoffee.com"],
		["uk", "https://uk.codefixcoffee.com"],
		["au", "https://au.codefixcoffee.com"]
	];
	const CUR = "tr";
	const __exists = (l) => l === CUR || l === "en" ? true : (__man[l] ?? []).includes(__path);
	const __altTags = __all.filter(([l]) => __exists(l)).map(([l, b2]) => `<link rel="alternate" hreflang="${l}" href="${b2}${__path}" />`).join("\n  ");
	return renderTemplate`<html lang="LOC" data-locale="LOC"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}</title><meta name="description"${addAttribute(description, "content")}>${__altTags && renderTemplate`${renderComponent($$result, "Fragment", Fragment, {}, { "default": ($$result) => renderTemplate`${unescapeHTML(__altTags + "\n  ")}` })}`}<link rel="alternate" hreflang="x-default"${addAttribute(`https://codefixcoffee.com${__path}`, "href")}><link rel="canonical"${addAttribute(canonical, "href")}><meta property="og:title"${addAttribute(title, "content")}><meta property="og:description"${addAttribute(description, "content")}><meta property="og:type" content="article"><meta property="og:url"${addAttribute(canonical, "content")}><meta property="og:site_name"${addAttribute(SITE.name, "content")}><meta property="og:image"${addAttribute(new URL("/og-image.png", Astro.site), "content")}><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image"${addAttribute(new URL("/og-image.png", Astro.site), "content")}><link rel="icon" type="image/png" sizes="96x96" href="/favicon-96.png"><link rel="icon" type="image/png" sizes="48x48" href="/favicon-48.png"><link rel="icon" href="/favicon.ico" sizes="48x48 32x32 16x16"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="sitemap" href="/sitemap-index.xml">${allLd.map((ld) => renderTemplate`<script type="application/ld+json">${unescapeHTML(JSON.stringify(ld))}<\/script>`)}${SITE.adsenseClient && renderTemplate`${renderComponent($$result, "Fragment", Fragment, {}, { "default": ($$result) => renderTemplate`<meta name="google-adsense-account"${addAttribute(SITE.adsenseClient, "content")}><script async${addAttribute(`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${SITE.adsenseClient}`, "src")} crossorigin="anonymous"><\/script>` })}`}${SITE.cfAnalyticsToken && renderTemplate`<script defer src="https://static.cloudflareinsights.com/beacon.min.js"${addAttribute(`{"token": "${SITE.cfAnalyticsToken}"}`, "data-cf-beacon")}><\/script>`}${renderHead($$result)}</head><body>${renderComponent($$result, "LangNav", $$LangNav, { "path": canonical.pathname })}<header class="site"><div class="in"><a class="brand" href="/">☕ ${SITE.name}</a><nav><a href="/breville">Breville</a><a href="/jura">Jura</a><a href="/philips-saeco">Philips / Saeco</a><a href="/delonghi">De&#39;Longhi</a><a href="/ge">GE</a><a href="/samsung">Samsung</a></nav></div></header><main>${crumbs.length > 0 && renderTemplate`<nav class="crumbs" aria-label="Breadcrumb">${crumbs.map((c, i) => renderTemplate`${renderComponent($$result, "Fragment", Fragment, {}, { "default": ($$result) => renderTemplate`${i > 0 && " › "}<a${addAttribute(c.href, "href")}>${c.name}</a>` })}`)}</nav>`}${renderSlot($$result, $$slots["default"])}${renderComponent($$result, "AdSlot", $$AdSlot, { "slot": SITE.adSlotFooter })}</main><footer><div>${SITE.name} — independent repair reference. Not affiliated with any manufacturer. Service-mode instructions are for information; opening a machine may void its warranty. Last reviewed ${SITE.updated}.</div><div><a href="/about">About</a><a href="/privacy">Privacy</a><a href="/contact">Contact</a></div></footer></body></html>`;
}, "/Users/kinsey/niche-site-tr/src/layouts/Base.astro", void 0);
//#endregion
export { $$AdSlot as n, createComponent as r, $$Base as t };
